### ISSUE TITLE
WARNING (MainThread) [aiowaqi] 'neph' is an unsupported value for <enum 'Pollutant'>

### ISSUE THREAD

**Issue by jonwaland** [joostlek/python-waqi#91]
# Problem/Motivation
Home Assistant 2023.10.3

`2023-10-17 14:01:45.039 WARNING (MainThread) [aiowaqi] 'neph' is an unsupported value for <enum 'Pollutant'>, please report this at https://github.com/joostlek/python-waqi/issues`

## Expected behavior

> (What you expected to happen)

## Actual behavior

`2023-10-17 14:01:45.039 WARNING (MainThread) [aiowaqi] 'neph' is an unsupported value for <enum 'Pollutant'>, please report this at https://github.com/joostlek/python-waqi/issues`

## Steps to reproduce

```
- platform: waqi
  token: xxxxxxx
  locations:
    - Macquarie Park Sydney East
```

## Proposed changes

none
